name: Simple Test

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World! GitHub Actions is working!"
        
      - name: Check files
        run: ls -la 